replicaCount: 1
image:
  repository: lukaosmani/website-blue
  tag: v1.0.0
color: blue
releaseName: blue-website
service:
  type: ClusterIP
  port: 80
  servicename: blue-website-service
ingress:
  enabled: true
  host: blue.luka.com
  pathType: Prefix
  tls:
    enabled: false
    secretName: blue-secret
