replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  pathType: Prefix

pdb:
  minAvailable: 1

deployments:
  - name: yellow-website
    namespace: yellow
    minAvailable: 1
  - name: green-website
    namespace: green
    minAvailable: 1
  - name: blue-website
    namespace: blue
    minAvailable: 1
