apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: website-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: blue
            path: blue
          - name: green
            path: green
          - name: yellow
            path: yellow
  template:
    metadata:
      name: '{{name}}-website'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/lukaosmani/website.git'
        targetRevision: main
        path: '.'
        helm:
          valueFiles:
            - '{{path}}/values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
