apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: website-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: blue
            additionalValuesFile: values-blue.yaml
          - name: green
            additionalValuesFile: values-green.yaml
          - name: yellow
            additionalValuesFile: values-yellow.yaml
  template:
    metadata:
      name: '{{name}}-website'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/lukaosmani/website'
        targetRevision: main
        path: '.'
        helm:
          valueFiles:
            - values.yaml
            - '{{additionalValuesFile}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
