apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    color: {{ .Values.color }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      color: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        color: {{ .Values.color }}
    spec:
      containers:
        - name: {{ .Values.color }}
          image: "lukaosmani/website-{{ .Values.color }}:v1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
