apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.releaseName }}
  labels:
    app: {{ .Values.releaseName }}
    color: {{ .Values.color }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.releaseName }}
      color: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: {{ .Values.releaseName }}
        color: {{ .Values.color }}
    spec:
      containers:
        - name: {{ .Values.color }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
