apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.releaseName | default .Release.Name }}
  labels:
    app: {{ .Values.releaseName | default .Release.Name }}
    color: {{ .Values.color | default "default-color" }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.releaseName | default .Release.Name }}
      color: {{ .Values.color | default "default-color" }}
  template:
    metadata:
      labels:
        app: {{ .Values.releaseName | default .Release.Name }}
        color: {{ .Values.color | default "default-color" }}
    spec:
      containers:
        - name: {{ .Values.color | default "default-color" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
