{{- range .Values.deployments }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app: {{ $.Release.Name }}-{{ .name }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: 80
  selector:
    app: {{ $.Release.Name }}-{{ .name }}
---
{{- end }}
