apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.servicename | default .Values.releaseName | default "default-service" }}
  labels:
    app: {{ .Values.releaseName | default "default-release" }}
    color: {{ .Values.color | default "default-color" }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 80
  selector:
    app: {{ .Values.releaseName | default "default-release" }}
    color: {{ .Values.color | default "default-color" }}
