apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.servicename | default (printf "%s-service" .Release.Name) }}
  labels:
    app: {{ .Values.releaseName | default .Release.Name }}
    color: {{ .Values.color | default "default-color" }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 80
  selector:
    app: {{ .Values.releaseName | default .Release.Name }}
    color: {{ .Values.color | default "default-color" }}
