replicaCount: 1
image:
  tag: blue
color: blue
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  hosts:
    - host: blue.luka.com
      paths:
        - path: /
          pathType: ImplementationSpecific
